### ISSUE TITLE
Incorrect creating of a project with spaced in name

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#158]
Name `___@@@`

<img width="976" alt="image" src="https://user-images.githubusercontent.com/3684889/71311675-2a9b3180-2432-11ea-8315-6d22fbf9201f.png">

Name `_New`

<img width="274" alt="image" src="https://user-images.githubusercontent.com/3684889/71311678-3129a900-2432-11ea-8858-4567bdb865b9.png">

**Comment by GeekaN2** [comment]
Не получается воспроизвести эту ошибку, может есть другие инструкции или уже всё пофиксили?
![изображение](https://user-images.githubusercontent.com/40016207/79351690-6c586680-7f52-11ea-9395-dece9ecd25c0.png)

**Comment by neSpecc** [comment]
Вместо нижних подчеркиваний поставь пробелы: 

<img width="275" alt="image" src="https://user-images.githubusercontent.com/3684889/79352001-fba94e00-7f41-11ea-86d9-734142ed630a.png">
