### ISSUE TITLE
Create Project Settings page

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#171]
- Projects settings opened in popup (already done)
- In popup we have three menu items: Project Settings, Integrations, Notifications
- You need to create `Project settings` page
-  There is a form on `Project settings` page: title, description, logo. Form is similar with Workspace Settings

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/3684889/74485075-f8a2ca80-4eca-11ea-80f5-e869939e4489.png">

**Comment by neSpecc** [comment]
Project settings popup can be opened from project header:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/3684889/74485336-94ccd180-4ecb-11ea-85fe-fe9b23762509.png">

**Comment by nikmel2803** [comment]
done
