### ISSUE TITLE
Resolve, Star, Ignore events

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#197]
1. В шапке Event Overview добавятся кнопки `Resolve`, `Star`, `Ignore`

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/3684889/76746348-6c651b00-6788-11ea-8c64-42b7d9e1d69f.png">

(Новая шапка в разработке еще #190, так что можно пока сделать временные кнопки в старой шапке)

2. Надо спроектировать то, как эти флаги будут храниться в базе. Возможно, в полях `isStarred`, `isIgnored`, `isResolved` коллекции `events:<projectId>`.

3. Добавить мутации в api/гараже для обновления этих статусов

4. В списке ивентов (Project Overview) слева перед датой выводить статусы. Если статуса нет — серый кружок.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/3684889/76746717-01681400-6789-11ea-8485-18f83517f258.png">

4.1 Ошибки со статусом `isIgnored` выводить в списке с прозрачносью 20%
4.2 Статус  `isIgnored` должен распространяться в том числе на все последующие повторения ивента в других днях.
4.3 У ошибки со статусом `isResolved` бейдж и тайтл должны быть серыми, как у просмотренной.

**Comment by nikmel2803** [comment]
resolved via #198
