### ISSUE TITLE
Recover password with wrong email

### ISSUE THREAD

**Issue by ilyamore88** [codex-team/hawk.garage#269]
When new user try to recover password, he gets a success message:
![image](https://user-images.githubusercontent.com/37909603/83977583-390ad600-a90a-11ea-882f-e3fe8273d9ad.png)
But he should see error.

**Comment by neSpecc** [comment]
This is the expected behaviour because user should not have an ability to check if some email is registered in a Hawk

**Comment by nikmel2803** [comment]
resolved
