### ISSUE TITLE
Chart trimmed on the Linux

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#274]
See the last day

![изображение](https://user-images.githubusercontent.com/3684889/86394871-eb368300-bca7-11ea-833e-4fc0fcdad282.png)

**Comment by ilyamore88** [comment]
On the Windows too. I think it's related to Firefox.
![image](https://user-images.githubusercontent.com/37909603/118618495-590a7100-b7cc-11eb-95a6-ca3b7ab3e330.png)

**Comment by ilyamore88** [comment]
Doesn't reproduce in Chrome.
![image](https://user-images.githubusercontent.com/37909603/118618574-6e7f9b00-b7cc-11eb-9fd0-7789fa2332e7.png)
