### ISSUE TITLE
Как пользователь, я хочу видеть уведомление о последствиях, если поменяю тарифный план

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/hawk.garage#330]

**Comment by neSpecc** [comment]
Use the universal `Confirmation` component. Design here https://github.com/codex-team/hawk.garage/issues/259

**Comment by neSpecc** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/3684889/115145139-c3f34b80-a058-11eb-9036-de1fe5fc77b0.png">

Text: 

```
You are about to change the CodeX tariff plan. Your current conditions including the left events limit and paid days will be lost. Read more about plan-changing [link to docs / pricing faq]. 
```

**Comment by neSpecc** [comment]
Confirmation should be opened when a user is about to proceed with payment:
- after he clicked on the `Proceed subscription` on the Billing Popup
- before he will see the Cloud payment form

**Comment by nikmel2803** [comment]
implemented
