### ISSUE TITLE
Как администратор, я хочу видеть в списке платежей, чтобы легко идентифицировать назначение платежа

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.garage#356]
`CDX 21-01 Basic` (от CodeX за январь 2021, за план Basic)

https://github.com/codex-team/hawk.garage/blob/9a63ff968ffc48bd3fdd70963a8f4979ccb5fa1f/src/components/modals/ProcessPaymentDialog.vue#L150

**Comment by nikmel2803** [comment]
done
