### ISSUE TITLE
Как администратор, я хочу видеть понятные invoiceId, чтобы понимать смысл транзакций

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#360]
| Дано | Когда | Тогда |
| ----- | ------ | ------ | 
| Админ воркспейса CodeX |  Нажимает Оплатить план Basic 4 февраля 2021 года  | Геренируется invoiceId: `CDX 21-02-04 Basic` |

<img width="967" alt="image" src="https://user-images.githubusercontent.com/3684889/106936145-44c6ca80-672d-11eb-83dc-da373537941c.png">

**Comment by nikmel2803** [comment]
done

**Comment by neSpecc** [comment]
Dublicate https://github.com/codex-team/hawk.api.nodejs/issues/288
