### ISSUE TITLE
Как владелец, я хочу, чтобы нельзя было оплатить план за другой проект

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.garage#361]
| Дано | Когда | Тогда |
| ----- | ------ | ------ | 
| Виджет Cloudpayments | Я подменяю `workspaceId` в поле data | В одном из коллбэков биллинга должна выпасть ошибка и отправиться лог в телеграм |

Вот [сюда](https://github.com/codex-team/hawk.garage/blob/master/src/types/plan-prolongation-payload.ts) надо добавить поле hash. Весь payload надо запрашивать с бэкенда.

 Также, надо передавать тарифный план, за который производится оплата. Его тоже надо проверить в коллбэке биллинга. Тут хэш не нужен, достаточно проверить, соответсвутет ли оплаыенная сумма цене этого плана =

**Comment by nikmel2803** [comment]
done
