### ISSUE TITLE
Как пользователь, я хочу видеть стоимость платежа, чтобы понимать, сколько я должен оплатить

### ISSUE THREAD

**Issue by ilyamore88** [codex-team/hawk.garage#368]
| Дано | Когда | Тогда |
| ----- | ------ | ------ | 
|  ![image](https://user-images.githubusercontent.com/37909603/109399985-24b6af80-7957-11eb-9045-ac3efa339b40.png) | Смена тарифного плана на платный | Видеть размер платежа в поле `Amount` |

**Comment by nikmel2803** [comment]
done
<img width="717" alt="image" src="https://user-images.githubusercontent.com/32655339/115138214-89c38300-a033-11eb-8364-6052cfe3d286.png">
