### ISSUE TITLE
As a user I want to see an Events Limit or a notification about a low limit rate to update the tariff

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/hawk.garage#400]
| Given |When | Then |
| ----- | ------ | ------ | 
| User visits Garage | Limit almost reached | User understand it |

**Comment by neSpecc** [comment]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/3684889/115147281-f4d87e00-a062-11eb-9a84-7802fa71e352.png">
