### ISSUE TITLE
Troubles with plan while creating a new workspace

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.garage#545]
![image](https://user-images.githubusercontent.com/15259299/140791601-28443124-1506-42a7-9c36-eaa2282179a5.png)

**Comment by talyguryn** [comment]
Reload page will fix it. But the problem is on the front side.

**Comment by robonetphy** [comment]
According @talyguryn it not occurring and I also tested many but this error is not reproducible. So if it occurs pls open it in future.

**Comment by robonetphy** [comment]
![IMG-20211216-WA0005](https://user-images.githubusercontent.com/23169768/146390102-8576f72c-4932-43f3-a0dc-9841f4c29e0d.jpg)
