### ISSUE TITLE
As a user I don't want to see 'add new card' button because it's unclickable

### ISSUE THREAD

**Issue by GeekaN2** [codex-team/hawk.garage#577]
Need to remove a block with this button, because we can't add a new card via that button.
<img width="281" alt="изображение" src="https://user-images.githubusercontent.com/40016207/153443060-51d61eda-5ece-4019-8868-775cd30baeab.png">

**Comment by neSpecc** [comment]
We have a card saving, isn't it?

**Comment by GeekaN2** [comment]
We have, but this button do nothing. So we should show this block only if we have at least one connected card
